### ISSUE TITLE
I get an error after install all the dependencies and the library

### ISSUE THREAD

**Issue by Pmarenco** [ozancaglayan/python-emotiv#13]
Traceback (most recent call last):
  File "epoc.py", line 442, in <module>
    sys.exit(main())
  File "epoc.py", line 416, in main
    e = EPOC()
  File "epoc.py", line 173, in __init__
    self.enumerate()
  File "epoc.py", line 208, in enumerate
    print "Devices found: %d" % len(devices)
TypeError: object of type 'generator' has no len()

**Comment by ixjlyons** [comment]
This is a duplicate of issue #12. See my comment there for a fix.

**Comment by ozancaglayan** [comment]
Merged the fix.
