### ISSUE TITLE
Error after dependency

### ISSUE THREAD

**Issue by diegoaguilar** [ozancaglayan/python-emotiv#18]
I just installed the lib with proper sudo privileges, I also got both pysub and pycrypto installed.

However, after `sudo python epoc.py` I'm getting following error output:

```
[Errno None] error sending control message: Broken pipe
Traceback (most recent call last):
  File "epoc.py", line 439, in <module>
    sys.exit(main())
  File "epoc.py", line 413, in main
    e = EPOC()
  File "epoc.py", line 173, in __init__
    self.enumerate()
  File "epoc.py", line 246, in enumerate
    self.setup_encryption()
  File "epoc.py", line 263, in setup_encryption
    self.decryption_key = ''.join([self.serial_number[15], '\x00',
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by michaelBiochemist** [comment]
What I found out was that the epoc is not correctly picking up the serial number. What you can do is look up the serial number while the epoc dongle is plugged in with the code:
`devices = usb.core.find(find_all=True)
for dev in devices:
    print dev`
copy this data to a file and search for the Emotiv device, find the serial number. Replace where it instantiates the object with `e = EPOC(serial_number=<your_serial_number_here>)`
It's also worth noting that i replaced "devices = usb.core.find(find_all=True, custom_match=self._is_epoc)" with "devices = usb.core.find(find_all=True)"
