### ISSUE TITLE
A problem when start "emotiv/epoc.py"

### ISSUE THREAD

**Issue by aloz01** [ozancaglayan/python-emotiv#20]
> python epoc.py

```
Traceback (most recent call last):
  File "epoc.py", line 439, in <module>
    sys.exit(main())
  File "epoc.py", line 413, in main
    e = EPOC()
  File "epoc.py", line 173, in __init__
    self.enumerate()
  File "epoc.py", line 210, in enumerate
    for dev in devices:
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 1249, in device_iter
    if _interop._all(tests) and (custom_match is None or custom_match(d)):
  File "epoc.py", line 178, in _is_epoc
    manu = usb.util.get_string(device, device.iManufacturer)
  File "/usr/local/lib/python2.7/dist-packages/usb/util.py", line 314, in get_string
    raise ValueError("The device has no langid")
ValueError: The device has no langid

```
Thanks..

**Comment by samisabik** [comment]
Have you find a solution ?
